// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styled from '@emotion/styled'
import { useRouter } from 'next/router'

const Wrap = styled.div`
  width: 100%;
  height: 100vh;
  background-image: url('./paper.jpg');
  background-size: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`
const LOGO = styled.h1`
  font-size: 50px;
`
const ClickBTN = styled.div`
  width: 80px;
  height: 30px;
  text-align: center;
  line-height: 30px;
  border: none;
  border-radius: 5px;
  background-color: #555;
  opacity: 65%;
  color: #fff;
  margin-top: 30px;
  cursor: pointer;
  :hover {
    background-color: #9b111e;
  }
`

export default function Home() {
  const router = useRouter()
  function onClickPortfolio() {
    router.push('/market/list')
  }
  return (
    // <div className={styles.container}>
    <Wrap>
      <>
        <LOGO>○ △ □</LOGO>
        <p>입장을 원하시면 아래 버튼을 눌러주세요.</p>
        <ClickBTN onClick={onClickPortfolio}>Click</ClickBTN>
      </>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
      {/* </span>
        </a>
      </footer> */}
    </Wrap>
    // {/* </div> */}
  )
}
